### ISSUE TITLE
API Implementation TODO List

### ISSUE THREAD

**Issue by GabeALopez** [GabeALopez/python-job-emailer#1]
# APIs To Implement
## No Auth APIs

**NOTE: Arbeitnow is for Europe but could get work visa sponsorship**

- [ ] [Arbeitnow](https://documenter.getpostman.com/view/18545278/UVJbJdKh)
- [ ] [DevITjobs](https://devitjobs.com/api/jobsLight) (Work in Progress)
- [ ] [GraphQL Jobs](https://graphql.jobs/docs/api/)
- [ ] [Open Skills](https://github.com/workforce-data-initiative/skills-api/wiki/API-Overview)

## Need Auth APIs

- [ ] [Adzuna](https://developer.adzuna.com/overview)
- [ ] [Arbeitsamt](https://jobsuche.api.bund.dev/)
- [ ] [Careerjet](https://www.careerjet.com/partners/api/)
- [ ] [Findwork](https://findwork.dev/developers/)
- [ ] [Jobs2Careers](http://api.jobs2careers.com/api/spec.pdf)
- [ ] [Jooble](https://jooble.org/api/about)
- [ ] [Juju](http://www.juju.com/publisher/spec/)
- [ ] [Reed](https://www.reed.co.uk/developers)
- [ ] [The Muse](https://www.themuse.com/developers/api/v2)
- [ ] [Upwork](https://developers.upwork.com/)
- [ ] [USAJOBS](https://developer.usajobs.gov/)
- [ ] [WhatJobs](https://www.whatjobs.com/affiliates)
- [ ] [ZipRecruiter](https://www.ziprecruiter.com/publishers)
